# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title2
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://nielsnuebel.github.io"
twitter_username: jekyllrb
github_username:  jekyll
googleanalyticss:  UA-XXXXX-1

# Build settings
markdown: kramdown


#Exclude Files or Folder
exclude: [node_modules, gulpfile.js, package.json, bower_components, bower.json, Gemfile, Gemfile.lock, README.md]
sass:
  sass_dir: _sass
  style: compressed

repository: nielsnuebel/anwalt

# Site nav
nav:

- name: Home
  link: "http://www.comedycentral.tv/"

- name: Shows
  link: "http://www.comedycentral.tv/shows/alle"

- name: News
  link: "http://www.comedycentral.tv/news"

- name: Funny Clips
  link: "http://de.funnyclips.cc/"

- name: TV-Programm
  link: "http://www.comedycentral.tv/programm"

- name: South Park
  link: "http://www.southpark.de/"

- name: Blog
  link: "http://www.comedycentral.tv/bestellt"

- name: Stand-Up Comedy
  link: "http://standup.comedycentral.de/"

# Microsite - Quotes Landing Page
quotes:

- text: FAIL IN LOVE WITH MASUD.
  size: 5

- text: TIERPFLEGER FÜR ALLE, DIE SICH IM INTERNET ZUM AFFEN MACHEN.
  size: 4

- text: BRO KLICKT ALLES WEG, WAS NICHT BEI 3 OFFLINE IST.
  size: 5

- text: GEILER ALS SELBER KLICKEN? BRUDI BEIM KLICKEN ZUGUCKEN!
  size: 45

- text: LÄSSIGER BRO ZEIGT ALLES VON KATZEN BIS KOTZEN.
  size: 5

- text: "WEBCLIPS MIT MASUD: HART ABER FAIL."
  size: 5

- text: HAMMER TYP MIT PFERDESCHWANZ ZEIGT VOR PUBLIKUM DIE GANZ DICKEN DINGER.
  size: 4

- text: BRUDI BRINGT BURNER.
  size: 6

- text: BRO ZEIGT FRESHE FUNVIDEOS FÜR FOLLOWER.
  size: 5

- text: GUT INTEGRIERTER BABO EXPORTIERT INTERNETHITS INS WOHNZIMMER.
  size: 4

- text: HOCHMUT KOMMT VOR DEM FAIL.
  size: 6

- text: MASUD IST DAS HAARTESTE, WAS DAS WEB ZU BIETEN HAT.
  size: 45

- text: BRO HAT JETZT SHOW!
  size: 6